service: test-pokedex-explorer-gaction

package:
  exclude:
   - _/**

provider:
  name: aws
  runtime: nodejs6.10

  stage: dev
  region: us-west-2
  profile: test-pokedex-explorer-gaction

  cfLogs: true

functions:
  ai:
    handler: handler.ai
    events:
      - http:
          path: ai
          method: post

  random:
    handler: handler.random
    events:
      - http:
          path: random
          method: get

  status:
    handler: handler.status
    events:
      - http:
          path: status
          method: get